[package]
name = "pika-drivers"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.4.4", package = "libadwaita" }
gtk = { version = "0.6.6", package = "gtk4" }
