name: PikaOS Package Build & Release (Canary) (amd64-v3)

on:
  push:
    branches:
      - main
    paths:
      - '.github/release-canary-v3'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:canaryv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ vars.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ vars.KNOWN_HOSTS }}
        if_key_exists: replace
    
    - name: Update APT Cache
      run: apt-get update -y

    - name: Build Package
      run: ./mainv3.sh

    - name: Release Package
      run: ./release.sh
